= Configurer des VLANs
:revealjs_theme: league
:source-highlighter: highlight.js
:icons: font

== Étape 1 : Création des VLANs

Accéder au switch et créer les VLANs pour segmenter le réseau.

[source, bash]
----
Switch> enable
Switch# configure terminal
----

=== ...

Créer le VLAN 10 pour Thomas, Brigite, leur imprimante.

[source, bash]
----
Switch(config)# vlan 10
Switch(config-vlan)# name VLAN_Thomas_Brigite
----

=== ...

Créer le VLAN 20 pour Le Directeur des RH, et son imprimante .

[source, bash]
----
Switch(config)# vlan 20
Switch(config-vlan)# name VLAN_DRH
----

=== ...

Créer le VLAN 30 pour la secrétaire du DRH et son imprimante .

[source, bash]
----
Switch(config)# vlan 20
Switch(config-vlan)# name VLAN_Secretaire
----



=== Étape 2 : 

Assigner les ports des ordinateurs et imprimantes aux VLANs

=== ...

Assigner les ordinateurs de Thomas et Brigite au VLAN 10 :

=== ...

Pour Brigite (port FastEthernet 0/1) :

[source, bash]
----
Switch(config)# interface fastEthernet 0/1
Switch(config-if)# switchport mode access
Switch(config-if)# switchport access vlan 10
----

=== ...

Pour Thomas (port FastEthernet 0/2) :

[source, bash]
----
Switch(config)# interface fastEthernet 0/2
Switch(config-if)# switchport mode access
Switch(config-if)# switchport access vlan 10
----


Assigner l'imprimante du VLAN 10 (port FastEthernet 0/3) :

[source, bash]
----
Switch(config)# interface fastEthernet 0/3
Switch(config-if)# switchport mode access
Switch(config-if)# switchport access vlan 10
----

=== ...

Assigner les ordinateurs de DRH et son imprimante au VLAN 20 :

=== ...

Pour DRH (port FastEthernet 0/4) :

[source, bash]
----
Switch(config)# interface fastEthernet 0/4
Switch(config-if)# switchport mode access
Switch(config-if)# switchport access vlan 20
----

=== ...

Pour Imprimante (port FastEthernet 0/5) :

[source, bash]
----
Switch(config)# interface fastEthernet 0/5
Switch(config-if)# switchport mode access
Switch(config-if)# switchport access vlan 20
----

=== ...

Assigner l'imprimante du VLAN 20 (port FastEthernet 0/6) :

[source, bash]
----
Switch(config)# interface fastEthernet 0/6
Switch(config-if)# switchport mode access
Switch(config-if)# switchport access vlan 20
----


=== ...

Assigner l'ordinateur de la secrétaire du VLAN 30 (port FastEthernet 0/7)

[source, bash]
----
Switch(config)# interface fastEthernet 0/7
Switch(config-if)# switchport mode access
Switch(config-if)# switchport access vlan 30
----

=== ...

Assigner l'imprimante de la secrétaire du VLAN 30 (port FastEthernet 0/8)

[source, bash]
----
Switch(config)# interface fastEthernet 0/8
Switch(config-if)# switchport mode access
Switch(config-if)# switchport access vlan 30
----

== Étape 4 : Routage inter-VLAN (via un switch multicouche ou un routeur)

Pour que la sécrétaire (VLAN 20) puisse accéder à l'imprimante du DRH (VLAN 20), vous devez activer le routage inter-VLAN.

=== ...

Configurer un switch multicouche (par exemple, un Cisco 3560) pour activer le routage entre les VLANs :

=== ...

Configuration de l'interface VLAN 10 (pour le réseau de Thomas et Brigite) :

[source, bash]
----
Switch(config)# interface vlan 10
Switch(config-if)# ip address 192.168.10.1 255.255.255.0
----

=== ...

Configuration de l'interface VLAN 20 (pour le DRH et son imprimante) :

[source, bash]
----
Switch(config)# interface vlan 20
Switch(config-if)# ip address 192.168.20.1 255.255.255.0
----

=== ...

Configuration de l'interface VLAN 30 (pour la sécrétaire et son imprimante) :

[source, bash]
----
Switch(config)# interface vlan 30
Switch(config-if)# ip address 192.168.30.1 255.255.255.0
----

=== ...

Activer le routage inter-VLAN sur le switch :

[source, bash]
----
Switch(config)# ip routing
----

=== ...

Configurer les dispositifs pour utiliser la passerelle par défaut (les adresses IP du switch dans chaque VLAN) :

=== ...

Thomas, Brigite, et leur imprimante  (VLAN 10) utiliseront 192.168.10.1 comme passerelle.

=== ...

DRH et son imprimante (VLAN 20) utiliseront 192.168.20.1 comme passerelle.

=== ...

La secrétaire et son imprimante  (le VLAN 30) utiliseront 192.168.30.1 comme passerelle.







