= commande ip default-gateway

==  Introduction

La commande ip default-gateway sur un switch Cisco est utilisée pour configurer une passerelle par défaut (ou gateway). 

=== ...


Cette passerelle est l'adresse IP d'un routeur qui permet au switch de communiquer avec des réseaux situés en dehors de son propre sous-réseau.


=== ...

Pourquoi configurer une passerelle par défaut sur un switch ?


=== Accès à distance pour la gestion du switch :


Si le switch doit être administré depuis un autre réseau (par exemple, via SSH ou Telnet), ...

=== ...

il a besoin d'une passerelle pour envoyer et recevoir des paquets hors de son sous-réseau.

=== ...

La passerelle par défaut permet au switch de savoir où envoyer les paquets destinés à d'autres réseaux.



=== Communication inter-VLAN (dans le cas d'un switch de niveau 2) :

Sur un switch de niveau 2 (qui ne gère pas le routage), le switch ne peut pas communiquer directement entre les VLANs.

=== ...

Si vous avez des VLANs configurés sur le switch et que vous souhaitez que les appareils des différents VLANs puissent se connecter au switch pour l'administration, ...

=== ...

vous avez besoin d'une passerelle par défaut qui redirigera le trafic vers le routeur ou un switch de niveau 3.



=== Transfert de logs ou d'autres services réseau :

Si le switch doit envoyer des logs à un serveur sur un autre sous-réseau, ...

=== ...

la passerelle par défaut est nécessaire pour transmettre ces paquets vers le réseau distant.

=== ...

Cela peut aussi inclure d'autres services réseau (comme le SNMP, les serveurs de supervision, etc.).


=== Exemple de cas d'utilisation

Supposons que vous avez un réseau avec un sous-réseau 192.168.1.0/24, ...

=== ...

et que le switch a l'adresse 192.168.1.10 pour son interface de gestion (interface VLAN 1). 

=== ...

Le routeur du réseau a l'adresse 192.168.1.1 et sert de passerelle vers d'autres réseaux.



=== Sans passerelle par défaut : 

Le switch ne pourra pas communiquer avec des réseaux autres que 192.168.1.0/24. 

=== ...

Ainsi, il ne pourra pas être administré à distance depuis un autre sous-réseau.


=== Avec ip default-gateway 192.168.1.1 : 

Le switch sait qu’il doit envoyer tout le trafic pour des réseaux externes (non locaux) vers le routeur à 192.168.1.1. 

=== ...

Cela permet une gestion à distance, des mises à jour ou la collecte de logs via des réseaux externes.

== Différence avec un switch de niveau 3 (L3)


Sur un switch de niveau 3 (ou switch avec routage inter-VLAN), on utilise des routes statiques et ...

=== ...

une route par défaut configurée dans la table de routage (ip route 0.0.0.0 0.0.0.0 <gateway>), plutôt que ip default-gateway. 


=== ...

La commande ip default-gateway est donc spécifique aux switches de niveau 2, qui n’ont pas de capacités de routage.



Si vous avez configuré une sous-interface sur le routeur qui correspond au VLAN 10, ...

=== ...

et que votre switch a une adresse IP de gestion dans ce VLAN, alors, oui, cette configuration peut être suffisante pour permettre ...

=== ...

la communication entre le switch et d'autres réseaux, à condition que la communication reste dans le même VLAN.


== Explication en détail

Quand vous créez une sous-interface pour le VLAN 10 sur le routeur :

Le routeur devient le point de routage pour tous les dispositifs du VLAN 10, y compris le switch.

=== ...


Les appareils dans le VLAN 10 peuvent envoyer des paquets vers d'autres VLANs ou réseaux en passant par cette sous-interface.


== Scénarios où la passerelle par défaut n’est pas nécessaire

Si toutes les conditions suivantes sont réunies, la passerelle par défaut sur le switch peut ne pas être nécessaire :

=== ...

Le switch a une adresse IP de gestion dans le même VLAN (VLAN 10).

=== ...

Le routeur dispose d'une sous-interface avec une adresse IP dans le VLAN 10 et peut donc router le trafic pour ce VLAN.

=== ...

L'administration et la gestion du switch se font uniquement depuis le même VLAN ou des dispositifs configurés pour y accéder via le routage inter-VLAN du routeur.

=== ...

Dans ce cas, le switch peut utiliser la sous-interface du routeur comme passerelle implicite, et il n’est pas nécessaire de définir explicitement ip default-gateway sur le switch.


== Scénarios où la passerelle par défaut est nécessaire

Cependant, la commande ip default-gateway peut être nécessaire dans les situations suivantes :

=== Accès depuis un réseau extérieur au VLAN 10 : 

Si vous souhaitez administrer le switch depuis un autre sous-réseau ou réseau externe (par exemple, un autre site ou un réseau différent).


=== Communication avec des services réseau en dehors du VLAN 10 : 

Si le switch doit envoyer des logs ou interagir avec des serveurs (comme SNMP, syslog, ou NTP) situés dans d'autres VLANs ou sous-réseaux.


=== Redondance de routage : 

Si vous avez plusieurs routeurs et que le switch doit savoir vers quel routeur envoyer le trafic en cas de changement de configuration réseau.

== En résumé

Si votre gestion se limite au VLAN 10 et que la sous-interface est bien configurée sur le routeur, la passerelle par défaut n'est pas obligatoire.


=== ...

Si vous avez besoin de communiquer avec des réseaux externes au VLAN 10 ou de fournir un accès de gestion depuis d'autres sous-réseaux, ...

=== ...

alors ip default-gateway sur le switch reste une bonne pratique pour garantir la connectivité.

=== ...


Dans ce cas, pour permettre l'administration du switch depuis un autre VLAN ou réseau, il est essentiel de configurer une passerelle par défaut sur le switch.


== Pourquoi configurer ip default-gateway dans ce cas ?

=== Accès depuis d'autres réseaux : 

La commande ip default-gateway permet au switch de savoir vers quel routeur envoyer les paquets destinés à des réseaux externes au VLAN 10. 

=== ...

Sans cette passerelle, le switch ne saura pas comment répondre aux demandes de votre ordinateur situé dans un autre VLAN.


=== Communication avec d'autres VLANs : 

Même si le routeur a une sous-interface pour chaque VLAN, ...

=== ...

le switch de niveau 2 doit connaître une passerelle pour envoyer les paquets en dehors de son propre VLAN. 

La passerelle par défaut sur le switch jouera ce rôle.


=== Configuration recommandée

Si votre routeur a une sous-interface pour le VLAN 10 avec, par exemple, l'adresse 192.168.10.1, vous pouvez configurer le switch comme suit :

[source, bash]
----
Switch(config)# ip default-gateway 192.168.10.1
----

Ainsi, le switch enverra toutes les communications destinées aux réseaux extérieurs vers le routeur, ...

=== ...

qui se chargera du routage inter-VLAN et permettra à votre ordinateur de configurer le réseau, même s’il est dans un autre VLAN.















